# Generated by Django 4.1.4 on 2023-02-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=70, unique=True)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('company_branch', models.CharField(choices=[('Chicago', 'Chicago'), ('Amsterdam', 'Amsterdam'), ('Bucharest', 'Bucharest')], max_length=10)),
                ('department', models.CharField(max_length=70)),
                ('position', models.CharField(max_length=70)),
                ('personal_phone', models.CharField(max_length=70)),
                ('personal_mail', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('date_of_birth', models.CharField(max_length=70)),
                ('nationality', models.CharField(max_length=70)),
                ('photo', models.ImageField(blank=True, default=None, upload_to='employee_photos/%Y/%m/%d')),
                ('level_of_english', models.CharField(choices=[('Weak', 'Weak'), ('Communicative', 'Communicative'), ('Fluent', 'Fluent')], max_length=20)),
                ('native_language', models.CharField(max_length=70)),
            ],
        ),
    ]
